server:
  port: 12345

drzk:
  mqtt:
    host: tcp://127.0.0.1:1883
    qos: 0
    #MQTT 认证
    userName: admin
    password: publish
    connectionTimeout: 20   # 20 second
    keepAliveInterval: 20
    subscribeTopic:
      - book/update
      - +/apple

spring:
  profiles:
    active: dev