server:
  port: 12340

drzk:
  mqtt:
    host: tcp://192.168.53.14
#    host: tcp://192.168.53.211
    qos: 0
    userName: admin
    password: public
    connectionTimeout: 20   # 20 second
    keepAliveInterval: 20
    publishTopic: jy
    subscribeTopic:
      - book/update
      - +/apple

spring:
  profiles:
    active: dev